# Generated by Django 5.0.6 on 2024-05-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('preco', models.CharField(max_length=5)),
                ('quantidade', models.CharField(max_length=4)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
